//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pennant.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomersResponsible
    {
        public int CustomersResponsibleID { get; set; }
        public int CustomersID { get; set; }
        public int EquipmentID { get; set; }
        public System.DateTime DateOfCapture { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Equipment Equipment { get; set; }
    }
}
