//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pennant.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customers()
        {
            this.CustomersResponsible = new HashSet<CustomersResponsible>();
            this.Equipment1 = new HashSet<Equipment>();
            this.Equipment2 = new HashSet<Equipment>();
        }
    
        public int CustomersID { get; set; }
        public string SurnameCust { get; set; }
        public string NameCust { get; set; }
        public string PatronomycCust { get; set; }
        public string EmailCust { get; set; }
        public string PhoneCust { get; set; }
        public int GenderID { get; set; }
        public byte[] Photo { get; set; }
        public int PostID { get; set; }
        public int NumCabID { get; set; }
        public int UserID { get; set; }
        public Nullable<int> EquipmentID { get; set; }
        public Nullable<int> CustomersResponsibleID { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual NumCab NumCab { get; set; }
        public virtual Post Post { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomersResponsible> CustomersResponsible { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipment> Equipment1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipment> Equipment2 { get; set; }
    }
}
