//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pennant.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipment()
        {
            this.Customers = new HashSet<Customers>();
            this.CustomersResponsible = new HashSet<CustomersResponsible>();
        }
    
        public int EquipmentID { get; set; }
        public int TypeofEquipmentID { get; set; }
        public int ConditionID { get; set; }
        public byte[] Photo { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateOfDelivery { get; set; }
        public Nullable<System.DateTime> DateOfCapture { get; set; }
        public Nullable<int> SerNum { get; set; }
        public Nullable<int> CustomersID { get; set; }
        public Nullable<bool> Istooc { get; set; }
        public string DescriptionOP { get; set; }
    
        public virtual Condition Condition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customers> Customers { get; set; }
        public virtual Customers Customers1 { get; set; }
        public virtual Customers Customers2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomersResponsible> CustomersResponsible { get; set; }
        public virtual TypeofEquipment TypeofEquipment { get; set; }
    }
}
